[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_PAYMENT_API_URL = "https://seu-backend-url"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
